---
- hosts:  ubuntuos
  become: yes
  tasks:
  - name: install git on ubuntu node
    apt:
     namee: git
    ignore_errors: yes

  - name: install tree on ubuntu node
    apt:
     name: tree

  - name: install wget on ubuntu node
    apt:
     name: wget