---
- hosts: amazonos
  become: yes
  gather_facts: no
  tasks:
  - name: install git, tree, wget on nodes
    yum:
     name: "{{ item }}"
     state: present

    with_items:
     - git
     - tree
     - wget