---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver(apache2) on ubuntu node
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"

  - name: start apache2 service on ubuntu node
    service:
     name: apache2
     state: started
    when: ansible_os_family == "Debian"

  - name: install webserver(httpd) on amazon node
    yum:
     name: httpd
     state: present
    when: ansible_os_family == "RedHat"

  - name: start httpd service on amazon node
    service:
     name: httpd
     state: started
    when: ansible_os_family == "RedHat"
