---
- hosts: ubuntuos
  become: yes
  tasks:
  - name: install apache2 webserver on ubuntu18 node
    apt:
      name: apache2
      state: present

  - name: start apache2 service on node
    service:
      name: apache2
      state: started