---
# tasks file for mytomrole
- name: install tomcat
  yum:
   name: tomcat
   state: present

- name:  copy tom config file into all nodes
  template:
    src:  templates/mytomconfig.j2
    dest: /usr/share/tomcat/conf/tomcat.conf
  notify: starttomcat

- name:  Install Admin Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - tomcat-webapps
    - tomcat-admin-webapps

- name: coy tom user file into all nodes
  template:
    src: templates/mytomuser.j2
    dest: /usr/share/tomcat/conf/tomcat-users.xml
  notify: restarttomcat

- name:  to deploy ravi java file into tomcat-admin-webapps
  get_url:
   url: https://raviwebapp.s3.amazonaws.com/raviLogin-1.0.war
   dest: /usr/share/tomcat/webapps/raviLogin-1.0.war
   force_basic_auth: yes